name: Vars

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: vars
        run: |
          echo "${{ github.event.release.tag_name }}"
      - name: github
        run: |
          echo "${{ toJSON(github) }}"
      - name: env
        run: |
          echo "${{ toJSON(env) }}"
      - name: job
        run: |
          echo "${{ toJSON(job) }}"
      - name: steps
        run: |
          echo "${{ toJSON(steps) }}"
      - name: runner
        run: |
          echo "${{ toJSON(runner) }}"
      - name: needs
        run: |
          echo "${{ toJSON(needs) }}"
